from .user import UserViewset
from .roles import RoleViewSet
from .permission import PermissionViewSet
from .configurations import ConfigurationViewSet
from .products import ProductViewSet
from .shopping import ShoppingViewSet
from .products_all import ProductAllViewSet
from .sales import SalesViewSet
from .reports import ReportsViewSet