# Generated by Django 2.2.13 on 2021-01-14 16:04

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('sales_commission', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='AnnualGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('annual_goal', models.IntegerField()),
                ('goal_quetzales', models.FloatField()),
                ('is_active_goal', models.BooleanField(default=False)),
                ('goal_first_trimester', models.FloatField()),
                ('goal_second_trimester', models.FloatField()),
                ('goal_third_trimester', models.FloatField()),
                ('goal_fourth_trimester', models.FloatField()),
                ('goal_first_trimester_quetzal', models.FloatField()),
                ('goal_second_trimester_quetzal', models.FloatField()),
                ('goal_third_trimester_quetzal', models.FloatField()),
                ('goal_fourth_trimester_quetzal', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_programadores', models.IntegerField(default=0)),
                ('cantidad_diseñadores', models.IntegerField(default=0)),
                ('porcentaje_error', models.FloatField(default=0)),
                ('precio_nominal', models.FloatField(default=0)),
                ('porcentaje_comisionCanalVenta', models.FloatField(blank=True, default=0)),
                ('porcentaje_comisionVendedor', models.FloatField(blank=True, default=0)),
                ('total_comisionCanal', models.FloatField(blank=True, default=0)),
                ('total_comisionVendedor', models.FloatField(blank=True, default=0)),
                ('tiempo_total', models.IntegerField(blank=True, default=0)),
                ('semanas_proyecto', models.IntegerField(blank=True, default=0)),
                ('meses_proyecto', models.IntegerField(blank=True, default=0)),
                ('total_horasProyecto', models.IntegerField(blank=True, default=0)),
                ('total_semanasMargenError', models.IntegerField(blank=True, default=0)),
                ('total_horasMargenError', models.IntegerField(blank=True, default=0)),
                ('precio_baseDesarrollo', models.FloatField(blank=True, default=0)),
                ('gastos_adminitrativos', models.FloatField(blank=True, default=0)),
                ('total_horasAdministrativas', models.IntegerField(blank=True, default=0)),
                ('total_semanasAdministrativas', models.IntegerField(blank=True, default=0)),
                ('total_mesesAdministrativas', models.IntegerField(blank=True, default=0)),
                ('duracion_totalProyecto', models.IntegerField(blank=True, default=0)),
                ('precio_total', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_modules', models.CharField(blank=True, max_length=50, null=True)),
                ('history_points', models.IntegerField(blank=True, null=True)),
                ('history_points_error', models.IntegerField(blank=True, null=True)),
                ('total_history_points', models.IntegerField(blank=True, null=True)),
                ('total_start_hours', models.FloatField(blank=True, null=True)),
                ('total_start_hours_error', models.FloatField(blank=True, null=True)),
                ('total_hours', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuenasNoticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coin_code', models.CharField(max_length=5)),
                ('coin_type', models.CharField(blank=True, max_length=50, null=True)),
                ('change_type', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('cities', models.CharField(blank=True, max_length=12)),
                ('employee_number', models.IntegerField(blank=True, null=True)),
                ('annual_income', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=40)),
                ('linkedIn_page', models.CharField(blank=True, max_length=100)),
                ('facebook_page', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('week_for_month', models.FloatField()),
                ('hour_for_week', models.FloatField()),
                ('name_coo', models.CharField(max_length=50)),
                ('email_coo', models.EmailField(blank=True, max_length=254, null=True)),
                ('name_boss_design', models.CharField(max_length=50)),
                ('email_boss_design', models.EmailField(blank=True, max_length=254, null=True)),
                ('name_boss_finance', models.CharField(max_length=50)),
                ('email_boss_finance', models.EmailField(blank=True, max_length=254, null=True)),
                ('name_boss_support', models.CharField(max_length=50)),
                ('email_boss_support', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_staff', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_business', models.CharField(blank=True, max_length=16, null=True)),
                ('position', models.CharField(blank=True, max_length=40, null=True)),
                ('client_type', models.CharField(blank=True, max_length=14, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('quetzal', models.FloatField()),
                ('cycle_days', models.IntegerField(null=True)),
                ('possibility_won', models.BooleanField(default=False, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('possibility_of_closure', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, default='', max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LifeCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=40)),
                ('commission_percentage', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesFunnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=40)),
                ('percentage_line', models.FloatField()),
                ('ordering', models.TextField()),
                ('business_lines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_sales', to='api.BusinessLines')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_channels', to='api.SalesChannel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_type', models.CharField(max_length=30)),
                ('rate_for_hour', models.FloatField(blank=True, null=True)),
                ('rate_for_hour_priority_support', models.FloatField()),
                ('rate_for_hour_support_normal', models.FloatField()),
                ('rate_for_month', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_project', models.CharField(max_length=100)),
                ('name_type', models.CharField(max_length=14)),
                ('average_sprint', models.IntegerField()),
                ('error_range', models.FloatField()),
                ('month_support', models.IntegerField()),
                ('hour_for_support_month', models.FloatField()),
                ('hour_implementation', models.FloatField()),
                ('hour_for_QA', models.FloatField()),
                ('hour_userManual', models.FloatField()),
                ('hour_technicalManual', models.FloatField()),
                ('hour_deployment', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('vendedor_percentage', models.FloatField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('limit_date', models.DateField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.Leads')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=40)),
                ('leads_ordering', models.TextField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('sale_funnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_sales', to='api.SalesFunnel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=15)),
                ('permissions', models.ManyToManyField(related_name='permission', to='api.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Avatar')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MALE'), (1, 'FEMALE')], null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PercentageGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('percentage', models.FloatField()),
                ('percentage_quetzal', models.FloatField()),
                ('annual_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percentage_goals', to='api.AnnualGoal')),
                ('business_lines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percentage_goals', to='api.BusinessLines')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='leads',
            name='business_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.StageSales'),
        ),
        migrations.AddField(
            model_name='leads',
            name='coin_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ChangeCoin'),
        ),
        migrations.AddField(
            model_name='leads',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
        migrations.AddField(
            model_name='leads',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Contact'),
        ),
        migrations.AddField(
            model_name='leads',
            name='owner_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leads',
            name='sales_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SalesChannel'),
        ),
        migrations.AddField(
            model_name='leads',
            name='sales_funnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='api.SalesFunnel'),
        ),
        migrations.AddField(
            model_name='contact',
            name='life_cycles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LifeCycle'),
        ),
        migrations.AddField(
            model_name='contact',
            name='userowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Industry'),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starting_range', models.FloatField()),
                ('final_rank', models.FloatField()),
                ('percentage_commission', models.FloatField()),
                ('name_type', models.CharField(max_length=14)),
                ('name_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetRelationModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_modules', models.CharField(blank=True, max_length=50, null=True)),
                ('history_points', models.IntegerField(blank=True, null=True)),
                ('history_points_error', models.IntegerField(blank=True, null=True)),
                ('total_history_points', models.IntegerField(blank=True, null=True)),
                ('total_start_hours', models.FloatField(blank=True, null=True)),
                ('total_start_hours_error', models.FloatField(blank=True, null=True)),
                ('total_hours', models.FloatField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_relation_modules', to='api.Budget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='canal_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SalesChannel'),
        ),
        migrations.AddField(
            model_name='budget',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Leads'),
        ),
        migrations.AddField(
            model_name='budget',
            name='tipo_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TypeClient'),
        ),
        migrations.AddField(
            model_name='budget',
            name='tipo_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TypeProject'),
        ),
        migrations.AddField(
            model_name='budget',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Vendedor'),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousData', models.TextField()),
                ('currentData', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='api.Action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeExpensesHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TypeProject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdministrativeExpensesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_expense', models.CharField(blank=True, max_length=50, null=True)),
                ('number_hours', models.FloatField(blank=True, null=True)),
                ('total_quantity', models.FloatField(blank=True, null=True)),
                ('rate_hour', models.FloatField(blank=True, null=True)),
                ('total_hours', models.FloatField(blank=True, null=True)),
                ('administrative_expenses_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.AdministrativeExpensesHeader')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdministrativeExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_expense', models.CharField(blank=True, max_length=50, null=True)),
                ('number_hours', models.FloatField(blank=True, null=True)),
                ('total_quantity', models.FloatField(blank=True, null=True)),
                ('rate_hour', models.FloatField(blank=True, null=True)),
                ('total_hours', models.FloatField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Budget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
