# Generated by Django 2.2.13 on 2021-01-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeexpensesheader',
            name='type_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_typeProject', to='api.TypeProject'),
        ),
    ]
