# Generated by Django 2.2.13 on 2021-01-25 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210121_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeexpenses',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminmodules', to='api.Budget'),
        ),
    ]
