# Generated by Django 2.2.13 on 2021-01-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210124_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativeexpenses',
            name='administrative_expenses_header',
        ),
        migrations.RemoveField(
            model_name='administrativeexpenses',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='administrativeexpensesdetail',
            name='administrative_expenses_header',
        ),
        migrations.RemoveField(
            model_name='administrativeexpensesheader',
            name='type_project',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='canal_venta',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='tipo_cliente',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='tipo_proyecto',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='BudgetModules',
        ),
        migrations.RemoveField(
            model_name='budgetrelationmodule',
            name='budget',
        ),
        migrations.DeleteModel(
            name='AdministrativeExpenses',
        ),
        migrations.DeleteModel(
            name='AdministrativeExpensesDetail',
        ),
        migrations.DeleteModel(
            name='AdministrativeExpensesHeader',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='BudgetRelationModule',
        ),
    ]
