# Generated by Django 2.2.13 on 2021-01-29 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cant', models.IntegerField(default=0, verbose_name='cantidad')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='api.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
