# Generated by Django 2.2.13 on 2021-01-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='producto',
            new_name='prod',
        ),
    ]
