# Generated by Django 2.2.13 on 2021-01-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210130_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='price_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
