# Generated by Django 2.2.13 on 2021-01-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210130_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Existencia'),
        ),
    ]
