
from .user import UserSerializer, UserReadSerializer, UserPermissionReadSerializer, UserReportSerializer
from .configurations import ConfigurationSerializer,ConfigurationRegisterSerializer
from .products import ProductSerializer, ProductRegistroSerializer, ProductReportSerializer
from .roles import PermissionReadSerializer, RoleReadSerializer
from .permission import PermissionSerializer
from .shopping import ShoppingSerializer, ShoppingRegistroSerializer
from .sales import SalesSerializer, SalesRegistroSerializer